name: publish

on:
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js latest version
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: "npm"
      - name: Install dependencies
        run: pnpm ci
      - name: Build project
        run: pnpm run build --if-present
      - name: Archive production artifact
        uses: actions/upload-artifact@v3
        with:
          name: artifacts-production
          path: dist

  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js latest version
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: "npm"
      - name: Download production artifact
        uses: actions/download-artifact@v3
        with:
          name: artifacts-production
      - name: Publish to npm
        run: pnpm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
